# Generated by Django 2.2.12 on 2022-12-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20221221_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='chewtoy',
            name='toys',
            field=models.ManyToManyField(to='main_app.Dog'),
        ),
    ]
