# Generated by Django 2.2.12 on 2022-12-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_chewtoy_toys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chewtoy',
            old_name='toys',
            new_name='dogs',
        ),
    ]
