# Generated by Django 2.2.12 on 2022-12-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20221223_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chewtoy',
            old_name='breed',
            new_name='type',
        ),
    ]
